### ISSUE TITLE
Testing: Add Cypress to Todo App

### ISSUE THREAD

**Issue by codingbootcampseu** [GanyFeta/bootcamp-schedule#89]
Use Cypress to add e2e tests to your todo app and cover all important features with tests.

- [ ] Add new todo
- [ ] Filter todos
- [ ] Remove done todos
- [ ] Only allow todos with at least 5 characters
